### ISSUE TITLE
-t flag -- no help with passing -t to animegrep

### ISSUE THREAD

**Issue by auladinglese** [daniel-Jones/animegrep#1]
running animegrep on mkv file produces

> track not set (use -t [track number]). You kind find the subtitle track number using 'mkvinfo [file]'..

running mkvinfo gives me the subtitle track number

> Track number: 3 (track ID for mkvmerge & mkvextract: 2)

passing -t 2 or -t2 to animegrep produces

> Invalid input file index: 2.

animegrep -h 

> ./animegrep.sh [-d <directory> | -f <file> ] -t <track> -w <WORD> -m -h 

`animegrep` is a bash script that extracts the subtitles from an mkv video file, greps them for a specified word, parses them and extracts only that time frame from the source video file

-d <directory> sets a directory as your source media
-f <file> sets a file as your source media. You cannot set directory and files at the same time.
-t <track> Not Documented. 
-w <word> track number for your source media.
-m to merge multiple output files as one. Useful if you have -d `set.`

**Comment by daniel-Jones** [comment]
Heya, I don't really plan on doing anything with this script and its pretty broken, another user forked it a while ago and made improvements (https://github.com/sr229/animegrep). You'll probably have more luck using their version.
